offset:
  head_pan: 0
  head_tilt: 0
  l_ank_pitch: 0
  l_ank_roll: 0
  l_el: 0
  l_hip_pitch: -0.00698131700797732
  l_hip_roll: -0.01919862177193763
  l_hip_yaw: 0
  l_knee: -0.008726646259971646
  l_sho_pitch: 0
  l_sho_roll: 0
  r_ank_pitch: 0
  r_ank_roll: 0
  r_el: 0
  r_hip_pitch: 0
  r_hip_roll: 0
  r_hip_yaw: -0.01919862177193763
  r_knee: 0
  r_sho_pitch: 0
  r_sho_roll: 0